repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        files: \.(coffee|js|ts|json|md|yml|yaml)$
      - id: end-of-file-fixer
        files: \.(coffee|js|ts|json|md|yml|yaml)$