name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USER }}
        key: ${{ secrets.PROD_SSH_KEY }}
        script: |
          cd ~/ClodForest
          git pull origin main
          npm install --production
          sudo systemctl restart clodforest
          sleep 5
          # Check if service started successfully
          sudo systemctl is-active clodforest
          # Show the new version
          curl -s http://localhost:8080/api/health | jq '.version, .build'